# Generated by Django 4.0.6 on 2022-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0023_alter_archiveclass_releasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='tenderno',
            field=models.CharField(max_length=500),
        ),
    ]
