# Generated by Django 4.0.6 on 2022-07-29 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0026_alter_about_id_alter_archiveclass_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiryclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=2)),
                ('tenderno', models.CharField(max_length=200)),
                ('download', models.URLField(blank=True)),
                ('downloadname', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('releasedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('closingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='gemclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=2)),
                ('tenderno', models.CharField(max_length=200)),
                ('download', models.URLField(blank=True)),
                ('downloadname', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('releasedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('closingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='panelmentclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=2)),
                ('tenderno', models.CharField(max_length=200)),
                ('download', models.URLField(blank=True)),
                ('downloadname', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('releasedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('closingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='procurementclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=2)),
                ('tenderno', models.CharField(max_length=200)),
                ('download', models.URLField(blank=True)),
                ('downloadname', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('releasedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('closingdate', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='archiveclass',
            new_name='corigendumclass',
        ),
    ]
